CREATE TABLE comment(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    blog_id INTEGER NOT NULL,
    name VARCHAR(255) NOT NULL,
    comment VARCHAR(1024) NOT NULL,
    character INTEGER NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (blog_id) REFERENCES blog(id)
);