CREATE TABLE emoji(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    blog_id INTEGER NOT NULL,
    funny INTEGER NOT NULL DEFAULT 0,
    sad INTEGER NOT NULL DEFAULT 0,
    wow INTEGER NOT NULL DEFAULT 0,
    clap INTEGER NOT NULL DEFAULT 0,
    perfect INTEGER NOT NULL DEFAULT 0,
    love INTEGER NOT NULL DEFAULT 0,
    hard INTEGER NOT NULL DEFAULT 0,
    good INTEGER NOT NULL DEFAULT 0,
    mad INTEGER NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (blog_id) REFERENCES blog(id)
);

INSERT INTO emoji(blog_id) VALUES (1) 