version: "3.8"

services:
  mysql:
    image: mysql/mysql-server:5.7
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - web_api
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  redis:
    image: redis:6.0.9-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - web_api
  postgesql:
    image: postgres:12-alpine
    container_name: postgesql
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - ".env"
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
    networks:
      - web_api

networks:
  web_api:
    driver: bridge
