server:
  host: ${HOST}
  port: ${PORT}
  debug: true
  readTimeout: 5
  writeTimeout: 5
  contextTimeout: 5
  rateLimitPerSec: 10
  accessJWT: ${ACCESS_JWT}
  refreshJWT: ${REFRESH_JWT}
  jwtExpireTime: 86400
  timezone: Asia/Taipei

database:
  adapter: "sqlite3"
  host: "./sqlite3.db"
  username: ""
  password: ""
  db: ""
  port: ""
  maxConns: 20
  maxLiftimeConns: 7200

cache:
  adapter: "bigcache"
  maxLiftime: 10

redis:
  adapter: "redis"
  host: "127.0.0.1"
  username: ""
  password: ""
  port: ""
  db: 0
  maxConns: 20
  maxLiftimeConns: 7200

logger:
  development: false
  disableCaller: false
  disableStacktrace: false
  encoding: json
  level: info
  filename: assets/access.log
  fileMaxSize: 10
  fileMaxAge: 30
  fileMaxBackups: 5
  fileIsCompress: false