version: v1

server:
  host: 0.0.0.0
  port: 3000
  mode: debug
  timeout:
    read: 1000
    write: 1000

database:
  adapter: "sqlite3"
  datatype: "sqlite3"
  host: "./gorm.db"
  username: "root"
  password: ""
  port: ""
  max_conns: 20
  max_liftime_conns: 7200


toke:
  jwt: "secret"